//! Build script to track include_str! dependencies and
//! auto-generate rule file includes from resources/atelier/rules/.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    // Inject git commit hash into the binary for `atelier --version`
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs/");
    if let Ok(output) = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
    {
        if output.status.success() {
            let hash = String::from_utf8_lossy(&output.stdout).trim().to_string();
            let dirty = std::process::Command::new("git")
                .args(["status", "--porcelain"])
                .output()
                .map(|o| !o.stdout.is_empty())
                .unwrap_or(false);
            let suffix = if dirty {
                format!("{}+{}-dirty", env!("CARGO_PKG_VERSION"), hash)
            } else {
                format!("{}+{}", env!("CARGO_PKG_VERSION"), hash)
            };
            println!("cargo:rustc-env=ATELIER_VERSION={}", suffix);
        }
    }

    // Auto-discover and track all rule files in resources/atelier/rules/
    println!("cargo:rerun-if-changed=resources/atelier/rules/");
    let rules_dir = Path::new("resources/atelier/rules");
    if rules_dir.is_dir() {
        if let Err(e) = generate_rules_file(rules_dir) {
            eprintln!("cargo:warning=Failed to generate rules_gen.rs: {}", e);
        }
    }
}

fn generate_rules_file(rules_dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut rule_entries: Vec<(String, String)> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(rules_dir)?
        .filter_map(|e| e.ok())
        .filter(|e| {
            let name = e.file_name().to_string_lossy().to_string();
            name.ends_with(".md") || name.ends_with(".txt")
        })
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let filename = entry.file_name().to_string_lossy().to_string();
        let rel_path = format!("resources/atelier/rules/{}", filename);
        println!("cargo:rerun-if-changed={}", rel_path);

        // Generate a const name from filename: quality.md -> RULE_QUALITY
        let const_name = filename
            .trim_end_matches(".md")
            .trim_end_matches(".txt")
            .to_uppercase()
            .replace('-', "_");
        let const_name = format!("RULE_{}", const_name);

        rule_entries.push((filename, const_name));
    }

    // Generate rules_gen.rs with all includes and the RULE_FILES array
    let out_dir = std::env::var("OUT_DIR")?;
    let gen_path = Path::new(&out_dir).join("rules_gen.rs");
    let mut gen_file = fs::File::create(&gen_path)?;

    writeln!(
        gen_file,
        "// Auto-generated by build.rs — do not edit manually"
    )?;
    writeln!(gen_file, "// Generated from resources/atelier/rules/")?;
    writeln!(gen_file)?;

    // Use absolute path for include_str! since OUT_DIR is deep in target/
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let abs_rules_dir = Path::new(&manifest_dir).join("resources/atelier/rules");

    // Write include_str! constants
    for (filename, const_name) in &rule_entries {
        let abs_path = abs_rules_dir.join(filename);
        // Use forward slashes for include_str! paths (works on all platforms)
        let path_str = abs_path.display().to_string().replace('\\', "/");
        writeln!(
            gen_file,
            "pub(crate) const {}: &str = include_str!(\"{}\");",
            const_name, path_str
        )?;
    }

    writeln!(gen_file)?;

    // Write the RULE_FILES array
    writeln!(
        gen_file,
        "pub(crate) const RULE_FILES: &[(&str, &str)] = &["
    )?;
    for (filename, const_name) in &rule_entries {
        writeln!(gen_file, "    (\"{}\", {}),", filename, const_name)?;
    }
    writeln!(gen_file, "];")?;

    Ok(())
}
